spring:
  application:
    name: task

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # 'update' crea las tablas si no existen o las actualiza. 'create-drop' las recrea en cada inicio.
      ddl-auto: create-drop
    show-sql: true     # Muestra las consultas SQL en la consola
    properties:
      hibernate:
        format_sql: true # Formatea el SQL en la consola para que sea legible
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
  sql:
    init:
      mode: always
      resources: classpath:import.sql
server:
  port: 8080 # Puerto por defecto
